version:
  activitycoupon:
    service: 'v1_1_0'
  coupon:
    service: 'v1_1_0'
  customer:
    service: 'v1_0_0'
  dispatchrider:
    service: 'v1_1_0'
  hisorder:
    service: 'v1_1_0'
  interaction:
    service: 'v1_1_0'
  linkhub:
    service: 'v1_1_0'
  menunew:
    service: 'v1_1_0'
  login:
    service: 'v1_1_0'
  notification:
    service: 'v1_0_0'
  misc:
    service:
      phhs: 'v1_1_0'
  order:
    service:
      ios:
        phhs: 'v1_1_0'
      os:
        phhs: 'v1_1_0'
  orderservice:
    callback: 'v1_1_0'
    query: 'v1_1_0'
  pointnew:
    service: 'v1_1_0'
  promotion:
    service:
      phhs: 'v2_2_0'
  pay:
    service: 'v2_0_0'
    web:
      service: 'v1_1_0'
  packet:
    service: 'v1_1_0'
  storeInfo:
    service: 'v1_0_0'
  emap: 
    service: 'v1_1_0'
  jira: 
    service: 'v1_1_0'
  3rd: 
    console: 'v1_1_0'
    mcHub: 'v1_1_0'
    service: 'v1_1_0'
    service.baidu: 'v1_1_0'
    service.meituan: 'v1_1_0'
    service.eleme: 'v1_1_0'
    service.os: 'v1_1_0'
    service.tdd: 'v1_1_0'
    service.dianping: 'v1_1_0'
    service.netease: 'v1_1_0'
    service.didi: 'v1_1_0'
  presale:
    service: 'v1_1_0'
  prime:
    service: 'v1_1_0'
  point:
    service: 'v2_0_0'
  booking:
    service: 'v2_0_0'
properties:
  pay:
    brand: 'yum'
  login:
    brand: 'phhs'
  notification:
    brand: 'yum'
  emap:
    brand: 'yum'
  point:
    brand: 'phhs'
    
service-name:
  misc.service: EC.YUM.MISCNEW.SERVICE.V1_1_0
  storeinfo.service: EC.PHHS.STOREINFO.SERVICE.V1_0_0
  emap.service: EC.YUM.EMAP.CORE.SERVICE.V1_1_0
  login.service: EC.PHHS.LOGIN.SERVICE.V1_1_0 
  middle.service: EC.PHHS.MISC.SERVICE.PHHS.V1_1_0 
  pointmall: pointMall.third.pm
  couponcenter: COUPONCENTER.THIRD.CC
  coupon.service: EC.PHHS.COUPON.SERVICE.V1_1_0
  passportnew: passportnew.third.pn
  creditnew: creditnew.third.cn
  virtualcard: virtualcard.third.vc
  pointnew.service: EC.PHHS.POINTNEW.SERVICE.V1_1_0
  menu.service: EC.PHHS.MENUNEW.SERVICE.V1_1_0
  notification.service: EC.YUM.NOTIFICATION.SERVICE.V1_0_0
  cmt.center: THIRDPARTY.PHHS.CMT
  couponws.center: THIRDPARTY.PHHS.COUPONWS
  custservice.center: THIRDPARTY.PHHS.CUSTSERVICE
  prime.center: THIRDPARTY.PHHS.PRIMECENTER
  membernew: membernew.third.pn
  sso.gateway: EC.PHHS.SSO.GATEWAY.V2_0_0
  sso.login.service: EC.PHHS.SSO.LOGIN.SERVICE.V2_0_0
  sso.userinfo.service: EC.PHHS.SSO.USERINFO.SERVICE.V2_0_0
  sso.support.service: EC.PHHS.SSO.SUPPORT.SERVICE.V2_0_0
  sso.passport.service: EC.YUM.SSO.PASSPORT.SERVICE.V2_0_0
  pay.service: EC.YUM.PAY.SERVICE.V2_0_0
  

#fallback-host:
 # misc.service: 119.3.102.34:1313
 # emap.service: 119.3.102.34:1414
 # storeinfo.service: 119.3.20.228:1415
 # notification.service: 122.112.203.78:1811
 # pay.service: 172.29.0.28:444
 # THIRDPARTY.YUM.MEMBER: 172.29.0.28:444
 # THIRDPARTY.YUM.PASSPORT: 172.29.0.28:444
 # THIRDPARTY.YUM.POINT: 172.29.0.28:444
 # THIRDPARTY.YUM.REWARD: 172.29.0.28:444
 # THIRDPARTY.YUM.VGOLD: 172.29.0.28:444
 # THIRDPARTY.YUM.VIRTUAL: 172.29.0.28:444
 # COUPONCENTER.THIRD.CC: 172.29.0.28:444
 # login.service: 172.29.0.28:444
  
  
#EC.YUM.MISCNEW.SERVICE.V1_1_0:
#  fallback-host: 119.3.102.34:1313
#EC.YUM.EMAP.CORE.SERVICE.V1_1_0:
#  fallback-host: 119.3.102.34:1414
#EC.PHHS.STOREINFO.SERVICE.V1_0_0:
 # fallback-host: 119.3.20.228:1415
#EC.YUM.NOTIFICATION.SERVICE.V1_0_0:
#  fallback-host: 122.112.203.78:1811
#EC.YUM.PAY.SERVICE.V2_0_0:
 # fallback-host: 172.29.0.28:444
#THIRDPARTY.YUM.MEMBER:
 # fallback-host: 172.29.0.28:444
#THIRDPARTY.YUM.PASSPORT:
 # fallback-host: 172.29.0.28:444
#THIRDPARTY.YUM.POINT:
  #fallback-host: 172.29.0.28:444
#THIRDPARTY.YUM.REWARD:
#  fallback-host: 172.29.0.28:444
#THIRDPARTY.YUM.VGOLD:
#  fallback-host: 172.29.0.28:444
#THIRDPARTY.YUM.VIRTUAL:
#  fallback-host: 172.29.0.28:444
#COUPONCENTER.THIRD.CC:
#  fallback-host: 172.29.0.28:444
#EC.PHHS.LOGIN.SERVICE.V1_1_0:
#  fallback-host: 172.29.0.28:444

  
logging:
  level:
    com:
      netflix:
        discovery: WARN
      yum: 
        client: INFO
    monitor:
        json: DEBUG

spring:
  sleuth:
    stream:
      enabled: false
      
feign.hystrix.enabled: true

hystrix:
  command.default.execution.isolation.strategy: SEMAPHORE
  command.default.execution.isolation.semaphore.maxConcurrentRequests: 50
  command.default.execution.timeout.enabled: false
